// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe1JVQ9v5tioSNa3oS5SGESpSKczZhCKw',
    appId: '1:862949506324:web:8eda1df9c10349677c9601',
    messagingSenderId: '862949506324',
    projectId: 'shoedealz-47938',
    authDomain: 'shoedealz-47938.firebaseapp.com',
    storageBucket: 'shoedealz-47938.firebasestorage.app',
    measurementId: 'G-5EEHN6KYTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe7NoYUL34QGwEuZHA_mP4n_bZC_FSvBc',
    appId: '1:862949506324:android:9b46148379948e777c9601',
    messagingSenderId: '862949506324',
    projectId: 'shoedealz-47938',
    storageBucket: 'shoedealz-47938.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB21N3tceMofNGze7TKvonjCoYN1sfY-Z0',
    appId: '1:862949506324:ios:c6d3dff30249ab747c9601',
    messagingSenderId: '862949506324',
    projectId: 'shoedealz-47938',
    storageBucket: 'shoedealz-47938.firebasestorage.app',
    iosBundleId: 'com.example.shoedealz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB21N3tceMofNGze7TKvonjCoYN1sfY-Z0',
    appId: '1:862949506324:ios:c6d3dff30249ab747c9601',
    messagingSenderId: '862949506324',
    projectId: 'shoedealz-47938',
    storageBucket: 'shoedealz-47938.firebasestorage.app',
    iosBundleId: 'com.example.shoedealz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe1JVQ9v5tioSNa3oS5SGESpSKczZhCKw',
    appId: '1:862949506324:web:39d1a3b0a36122a27c9601',
    messagingSenderId: '862949506324',
    projectId: 'shoedealz-47938',
    authDomain: 'shoedealz-47938.firebaseapp.com',
    storageBucket: 'shoedealz-47938.firebasestorage.app',
    measurementId: 'G-WFHBT2YMHD',
  );
}
